version : '3.8'
services:
  rabbitmq-demo:
    build: .
    container_name: rabbitmq-demo
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:3.9.27-management
    ports:
      - '5672:5672'
      - '15672:15672'
    